################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_UPPER_SRCS := 
O_SRCS := 
EEP_SRCS := 
C_UPPER_SRCS := 
CPP_SRCS := 
INO_SRCS := 
AR_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
ELF_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
CC_SRCS := 
C_DEPS := 
AR := 
FLASH_IMAGE := 
EEP := 
CXX_DEPS := 
S_UPPER_DEPS := 
ELF := 
C++_DEPS := 
ASM_DEPS := 
CC_DEPS := 
INO_DEPS := 
AR_OBJ := 
CPP_DEPS := 
LINK_OBJ := 
C_UPPER_DEPS := 
SIZEDUMMY := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
arduino/core \
arduino/core/avr-libc \
Libraries/Mozzi \
Libraries/Mozzi/examples/11.Communication/TwoWire_Read_ADXL345 \
Libraries/Mozzi/examples/11.Communication/Teensy_USB_MIDI_Input \
Libraries/Mozzi/examples/11.Communication/Sinewave_PWM_leds_HIFI \
Libraries/Mozzi/examples/11.Communication/Mozzi_Processing_Serial \
Libraries/Mozzi/examples/10.Audio_Filters/StateVariableFilter \
Libraries/Mozzi/examples/10.Audio_Filters/LowPassFilterX2 \
Libraries/Mozzi/examples/10.Audio_Filters/LowPassFilter \
Libraries/Mozzi/examples/09.Delays/ReverbTank_STANDARD \
Libraries/Mozzi/examples/09.Delays/AudioDelayFeedback_HIFI \
Libraries/Mozzi/examples/09.Delays/AudioDelayFeedbackX2 \
Libraries/Mozzi/examples/09.Delays/AudioDelayFeedbackAllpass \
Libraries/Mozzi/examples/09.Delays/AudioDelayFeedback \
Libraries/Mozzi/examples/09.Delays/AudioDelay \
Libraries/Mozzi/examples/08.Samples/Wavetable_Swap \
Libraries/Mozzi/examples/08.Samples/Samples_Tables_Arrays \
Libraries/Mozzi/examples/08.Samples/Samples \
Libraries/Mozzi/examples/08.Samples/Sample_Scrub \
Libraries/Mozzi/examples/08.Samples/Sample_Loop_Points \
Libraries/Mozzi/examples/08.Samples/SampleHuffman_Umpah \
Libraries/Mozzi/examples/08.Samples/Sample \
Libraries/Mozzi/examples/07.Envelopes/Phasemod_Envelope \
Libraries/Mozzi/examples/07.Envelopes/Ead_Envelope \
Libraries/Mozzi/examples/07.Envelopes/ADSR_Envelope_x2 \
Libraries/Mozzi/examples/07.Envelopes/ADSR_Envelope \
Libraries/Mozzi/examples/06.Synthesis/Waveshaper_Difference_Tone \
Libraries/Mozzi/examples/06.Synthesis/Waveshaper \
Libraries/Mozzi/examples/06.Synthesis/WavePacket_Single \
Libraries/Mozzi/examples/06.Synthesis/WavePacket_Sample \
Libraries/Mozzi/examples/06.Synthesis/WavePacket_Double \
Libraries/Mozzi/examples/06.Synthesis/PWM_Phasing \
Libraries/Mozzi/examples/06.Synthesis/FMsynth_HIFI \
Libraries/Mozzi/examples/06.Synthesis/FMsynth \
Libraries/Mozzi/examples/06.Synthesis/Detuned_Beats_Wash \
Libraries/Mozzi/examples/06.Synthesis/AMsynth_HIFI \
Libraries/Mozzi/examples/06.Synthesis/AMsynth \
Libraries/Mozzi/examples/05.Control_Filters/Thermistor_OverSample \
Libraries/Mozzi/examples/05.Control_Filters/Smooth_Frequency \
Libraries/Mozzi/examples/05.Control_Filters/Smooth \
Libraries/Mozzi/examples/05.Control_Filters/RollingAverage \
Libraries/Mozzi/examples/05.Control_Filters/MIDI_portamento \
Libraries/Mozzi/examples/05.Control_Filters/Line_vs_Smooth \
Libraries/Mozzi/examples/05.Control_Filters/DCfilter \
Libraries/Mozzi/examples/04.Audio_Input/Audio_and_Control_Input \
Libraries/Mozzi/examples/04.Audio_Input/Audio_Input_with_Knob_Filter \
Libraries/Mozzi/examples/04.Audio_Input/Audio_Input \
Libraries/Mozzi/examples/03.Sensors/Volume_Knob_LightLevel_Frequency \
Libraries/Mozzi/examples/03.Sensors/Volume_Knob \
Libraries/Mozzi/examples/03.Sensors/Sinewave_Pinchange_Interrupt \
Libraries/Mozzi/examples/03.Sensors/Piezo_Switch_Pitch \
Libraries/Mozzi/examples/03.Sensors/Piezo_SampleTrigger \
Libraries/Mozzi/examples/03.Sensors/Piezo_SampleScrubber \
Libraries/Mozzi/examples/03.Sensors/Piezo_Frequency \
Libraries/Mozzi/examples/03.Sensors/Light_Temperature_Multi_Oscil \
Libraries/Mozzi/examples/03.Sensors/Light_Temperature_Detuned \
Libraries/Mozzi/examples/03.Sensors/Knob_LightLevel_x2_FMsynth \
Libraries/Mozzi/examples/03.Sensors/Knob_LightLevel_FMsynth \
Libraries/Mozzi/examples/03.Sensors/Knob_LDR_x2_WavePacket \
Libraries/Mozzi/examples/02.Control/Pause \
Libraries/Mozzi/examples/02.Control/Metronome_SampleHuffman \
Libraries/Mozzi/examples/02.Control/Line_Gliss_Double_32k_HIFI \
Libraries/Mozzi/examples/02.Control/Line_Gliss \
Libraries/Mozzi/examples/02.Control/EventDelay \
Libraries/Mozzi/examples/02.Control/Control_Tremelo \
Libraries/Mozzi/examples/02.Control/Control_Oscil_Wash \
Libraries/Mozzi/examples/02.Control/Control_Echo_Theremin \
Libraries/Mozzi/examples/01.Basics/Vibrato \
Libraries/Mozzi/examples/01.Basics/Table_Resolution \
Libraries/Mozzi/examples/01.Basics/Skeleton \
Libraries/Mozzi/examples/01.Basics/Sinewave_HIFI \
Libraries/Mozzi/examples/01.Basics/Sinewave \
Libraries/Mozzi/examples/01.Basics/Control_Gain \

